// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw3n4ic1ST_28dV9--WLdIqo5uinoWrHg',
    appId: '1:682349141144:web:7cd67832f506fb653a04ed',
    messagingSenderId: '682349141144',
    projectId: 'authapp-2f8e6',
    authDomain: 'authapp-2f8e6.firebaseapp.com',
    storageBucket: 'authapp-2f8e6.appspot.com',
    measurementId: 'G-F36FMF9WHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlkWAf7nt85tIn7lsOyJppk5cqGL7t74w',
    appId: '1:682349141144:android:f97d2b5e273b48c53a04ed',
    messagingSenderId: '682349141144',
    projectId: 'authapp-2f8e6',
    storageBucket: 'authapp-2f8e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbO41En-BpqCapXZkcF-A_tTWbdeoqVVc',
    appId: '1:682349141144:ios:bf57ea40f4ab81e23a04ed',
    messagingSenderId: '682349141144',
    projectId: 'authapp-2f8e6',
    storageBucket: 'authapp-2f8e6.appspot.com',
    iosBundleId: 'com.example.authFireApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbO41En-BpqCapXZkcF-A_tTWbdeoqVVc',
    appId: '1:682349141144:ios:bd7f9e43bf8102833a04ed',
    messagingSenderId: '682349141144',
    projectId: 'authapp-2f8e6',
    storageBucket: 'authapp-2f8e6.appspot.com',
    iosBundleId: 'com.example.authFireApp.RunnerTests',
  );
}
